packages:
  - "packages/*"
  - "apps/*"

# Shared dependencies resolution with version alignment
catalogs:
  default:
    # Core React ecosystem
    react: "^18.3.1"
    react-dom: "^18.3.1"
    react-router-dom: "^6.26.2"
    
    # TypeScript & Tooling
    typescript: "^5.8.3"
    vite: "^5.4.19"
    "@types/react": "^18.3.3"
    "@types/react-dom": "^18.3.0"
    "@types/node": "^20.19.17"
    
    # Supabase & Querying
    "@supabase/supabase-js": "^2.54.0"
    "@tanstack/react-query": "^5.56.2"
    
    # UI & Styling
    tailwindcss: "^3.4.11"
    "class-variance-authority": "^0.7.1"
    clsx: "^2.1.1"
    "tailwind-merge": "^2.5.2"
    "lucide-react": "0.539.0"
    
    # Utilities
    "date-fns": "^3.6.0"
    sonner: "^1.5.0"
    
    # Linting & Dev Tools
    eslint: "^8.57.0"
    "@typescript-eslint/eslint-plugin": "^7.2.0"
    "@typescript-eslint/parser": "^7.2.0"
    "@vitejs/plugin-react": "^4.3.1"
