packages:
  - "packages/*"
  - "apps/*"

# Shared dependencies resolution
catalogs:
  default:
    react: "^18.2.0"
    react-dom: "^18.2.0"
    typescript: "^5.0.0"
    vite: "^5.0.0"
    "@types/react": "^18.2.0"
    "@types/react-dom": "^18.2.0"
