// This file is automatically generated. Do not edit manually.
// Generated from database schema at 2025-08-31T04:57:50.756Z
// Total tables processed: 74
// Tables with data: 10
// Tables inferred: 64

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          user_id: string;
          full_name: string | null;
          display_name: string | null;
          avatar_url: string | null;
          bio: string | null;
          verified_rank: string | null;
          elo: number;
          created_at: string;
          updated_at: string;
          is_admin: boolean;
          phone: string | null;
          skill_level: string;
          active_role: string;
          role: string;
          nickname: string | null;
          email: string | null;
          city: string | null;
          district: string | null;
          member_since: string;
          completion_percentage: number;
          is_demo_user: boolean;
          ban_status: string;
          ban_reason: string | null;
          banned_at: string | null;
          banned_by: string | null;
          cover_image_url: string | null;
          current_rank: string;
          spa_points: number;
          player_id: string;
          is_temp_player: boolean;
        };
        Insert: {
          id?: string;
          user_id?: string | undefined;
          full_name?: string | null;
          display_name?: string | null;
          avatar_url?: string | null;
          bio?: string | null;
          verified_rank?: string | null;
          elo?: number | undefined;
          created_at?: string | undefined;
          updated_at?: string | undefined;
          is_admin?: boolean | undefined;
          phone?: string | null;
          skill_level?: string | undefined;
          active_role?: string | undefined;
          role?: string | undefined;
          nickname?: string | null;
          email?: string | null;
          city?: string | null;
          district?: string | null;
          member_since?: string | undefined;
          completion_percentage?: number | undefined;
          is_demo_user?: boolean | undefined;
          ban_status?: string | undefined;
          ban_reason?: string | null;
          banned_at?: string | null;
          banned_by?: string | null;
          cover_image_url?: string | null;
          current_rank?: string | undefined;
          spa_points?: number | undefined;
          player_id?: string;
          is_temp_player?: boolean | undefined;
        };
        Update: {
          id?: string;
          user_id?: string;
          full_name?: string | null;
          display_name?: string | null;
          avatar_url?: string | null;
          bio?: string | null;
          verified_rank?: string | null;
          elo?: number;
          created_at?: string;
          updated_at?: string;
          is_admin?: boolean;
          phone?: string | null;
          skill_level?: string;
          active_role?: string;
          role?: string;
          nickname?: string | null;
          email?: string | null;
          city?: string | null;
          district?: string | null;
          member_since?: string;
          completion_percentage?: number;
          is_demo_user?: boolean;
          ban_status?: string;
          ban_reason?: string | null;
          banned_at?: string | null;
          banned_by?: string | null;
          cover_image_url?: string | null;
          current_rank?: string;
          spa_points?: number;
          player_id?: string;
          is_temp_player?: boolean;
        };
      };
      users: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          email: string;
          phone: string | null;
          status: string;
        };
        Insert: {
          id?: string;
          created_at?: string | undefined;
          updated_at?: string | undefined;
          email?: string | undefined;
          phone?: string | null;
          status?: string | undefined;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          email?: string;
          phone?: string | null;
          status?: string;
        };
      };
      user_roles: {
        Row: {
          id: string;
          user_id: string;
          role: string;
          created_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          user_id?: string | undefined;
          role?: string | undefined;
          created_at?: string | undefined;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          role?: string;
          created_at?: string;
          created_by?: string | null;
        };
      };
      user_preferences: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          id?: string;
          created_at?: string | undefined;
          updated_at?: string | undefined;
          user_id?: string | undefined;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          user_id?: string;
        };
      };
      user_sessions: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          id?: string;
          created_at?: string | undefined;
          updated_at?: string | undefined;
          user_id?: string | undefined;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          user_id?: string;
        };
      };
      auth_users: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          id?: string;
          created_at?: string | undefined;
          updated_at?: string | undefined;
          user_id?: string | undefined;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          user_id?: string;
        };
      };
      auth_sessions: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          created_at?: string | undefined;
          updated_at?: string | undefined;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      auth_refresh_tokens: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          created_at?: string | undefined;
          updated_at?: string | undefined;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      challenges: {
        Row: {
          id: string;
          challenger_id: string;
          opponent_id: string | null;
          status: string;
          challenge_message: string | null;
          response_message: string | null;
          created_at: string;
          responded_at: string | null;
          completed_at: string | null;
          is_open_challenge: boolean;
          bet_points: number;
          race_to: number;
          handicap_1_rank: string;
          handicap_05_rank: string;
          message: string;
          expires_at: string;
          challenge_type: string;
          handicap_data: Json;
          club_id: string;
          scheduled_time: string | null;
          challenger_score: number;
          opponent_score: number;
          winner_id: string | null;
          started_at: string | null;
          updated_at: string;
          challenger_name: string;
          location: string;
          required_rank: string;
          is_sabo: boolean;
          club_confirmed: boolean;
          club_confirmed_at: string | null;
          club_confirmed_by: string | null;
          club_note: string | null;
          challenger_player_id: string;
          opponent_player_id: string | null;
          bet_amount: number;
        };
        Insert: {
          id?: string;
          challenger_id?: string;
          opponent_id?: string | null;
          status?: string | undefined;
          challenge_message?: string | null;
          response_message?: string | null;
          created_at?: string | undefined;
          responded_at?: string | null;
          completed_at?: string | null;
          is_open_challenge?: boolean | undefined;
          bet_points?: number | undefined;
          race_to?: number | undefined;
          handicap_1_rank?: string | undefined;
          handicap_05_rank?: string | undefined;
          message?: string | undefined;
          expires_at?: string | undefined;
          challenge_type?: string | undefined;
          handicap_data?: Json | undefined;
          club_id?: string;
          scheduled_time?: string | null;
          challenger_score?: number | undefined;
          opponent_score?: number | undefined;
          winner_id?: string | null;
          started_at?: string | null;
          updated_at?: string | undefined;
          challenger_name?: string | undefined;
          location?: string | undefined;
          required_rank?: string | undefined;
          is_sabo?: boolean | undefined;
          club_confirmed?: boolean | undefined;
          club_confirmed_at?: string | null;
          club_confirmed_by?: string | null;
          club_note?: string | null;
          challenger_player_id?: string;
          opponent_player_id?: string | null;
          bet_amount?: number | undefined;
        };
        Update: {
          id?: string;
          challenger_id?: string;
          opponent_id?: string | null;
          status?: string;
          challenge_message?: string | null;
          response_message?: string | null;
          created_at?: string;
          responded_at?: string | null;
          completed_at?: string | null;
          is_open_challenge?: boolean;
          bet_points?: number;
          race_to?: number;
          handicap_1_rank?: string;
          handicap_05_rank?: string;
          message?: string;
          expires_at?: string;
          challenge_type?: string;
          handicap_data?: Json;
          club_id?: string;
          scheduled_time?: string | null;
          challenger_score?: number;
          opponent_score?: number;
          winner_id?: string | null;
          started_at?: string | null;
          updated_at?: string;
          challenger_name?: string;
          location?: string;
          required_rank?: string;
          is_sabo?: boolean;
          club_confirmed?: boolean;
          club_confirmed_at?: string | null;
          club_confirmed_by?: string | null;
          club_note?: string | null;
          challenger_player_id?: string;
          opponent_player_id?: string | null;
          bet_amount?: number;
        };
      };
      challenge_participants: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          created_at?: string | undefined;
          updated_at?: string | undefined;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      challenge_types: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          created_at?: string | undefined;
          updated_at?: string | undefined;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      game_sessions: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          created_at?: string | undefined;
          updated_at?: string | undefined;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      game_results: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          created_at?: string | undefined;
          updated_at?: string | undefined;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      shots: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          created_at?: string | undefined;
          updated_at?: string | undefined;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      shot_analysis: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          created_at?: string | undefined;
          updated_at?: string | undefined;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      game_mechanics: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          created_at?: string | undefined;
          updated_at?: string | undefined;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      game_settings: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          created_at?: string | undefined;
          updated_at?: string | undefined;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      tournaments: {
        Row: {
          id: string;
          name: string;
          description: string;
          tournament_type: string;
          game_format: string;
          tier_level: number;
          max_participants: number;
          current_participants: number;
          tournament_start: string;
          tournament_end: string;
          registration_start: string;
          registration_end: string;
          club_id: string;
          venue_address: string;
          entry_fee: number;
          prize_pool: number;
          first_prize: number;
          second_prize: number;
          third_prize: number;
          prize_distribution: Json;
          status: string;
          management_status: string;
          rules: string | null;
          contact_info: string | null;
          banner_image: string | null;
          min_rank_requirement: string | null;
          max_rank_requirement: string | null;
          eligible_ranks: Json;
          allow_all_ranks: boolean;
          requires_approval: boolean;
          is_public: boolean;
          has_third_place_match: boolean;
          created_by: string;
          created_at: string;
          updated_at: string;
          venue_name: string | null;
          start_date: string | null;
          end_date: string | null;
          registration_fee: number;
          is_visible: boolean;
          deleted_at: string | null;
          tier: string;
          elo_multiplier: number;
          live_stream_url: string | null;
          sponsor_info: Json;
          spa_points_config: Json;
          elo_points_config: Json;
          comprehensive_rewards: Json;
          special_rules: Json;
          tournament_format_details: Json;
          physical_prizes: Json;
          winner_id: string | null;
          parent_tournament_id: string | null;
          tournament_format: string | null;
          group_number: string | null;
          group_assignment_method: string | null;
        };
        Insert: {
          id?: string;
          name?: string | undefined;
          description?: string | undefined;
          tournament_type?: string | undefined;
          game_format?: string | undefined;
          tier_level?: number | undefined;
          max_participants?: number | undefined;
          current_participants?: number | undefined;
          tournament_start?: string | undefined;
          tournament_end?: string | undefined;
          registration_start?: string | undefined;
          registration_end?: string | undefined;
          club_id?: string;
          venue_address?: string | undefined;
          entry_fee?: number | undefined;
          prize_pool?: number | undefined;
          first_prize?: number | undefined;
          second_prize?: number | undefined;
          third_prize?: number | undefined;
          prize_distribution?: Json | undefined;
          status?: string | undefined;
          management_status?: string | undefined;
          rules?: string | null;
          contact_info?: string | null;
          banner_image?: string | null;
          min_rank_requirement?: string | null;
          max_rank_requirement?: string | null;
          eligible_ranks?: Json | undefined;
          allow_all_ranks?: boolean | undefined;
          requires_approval?: boolean | undefined;
          is_public?: boolean | undefined;
          has_third_place_match?: boolean | undefined;
          created_by?: string | undefined;
          created_at?: string | undefined;
          updated_at?: string | undefined;
          venue_name?: string | null;
          start_date?: string | null;
          end_date?: string | null;
          registration_fee?: number | undefined;
          is_visible?: boolean | undefined;
          deleted_at?: string | null;
          tier?: string | undefined;
          elo_multiplier?: number | undefined;
          live_stream_url?: string | null;
          sponsor_info?: Json | undefined;
          spa_points_config?: Json | undefined;
          elo_points_config?: Json | undefined;
          comprehensive_rewards?: Json | undefined;
          special_rules?: Json | undefined;
          tournament_format_details?: Json | undefined;
          physical_prizes?: Json | undefined;
          winner_id?: string | null;
          parent_tournament_id?: string | null;
          tournament_format?: string | null;
          group_number?: string | null;
          group_assignment_method?: string | null;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string;
          tournament_type?: string;
          game_format?: string;
          tier_level?: number;
          max_participants?: number;
          current_participants?: number;
          tournament_start?: string;
          tournament_end?: string;
          registration_start?: string;
          registration_end?: string;
          club_id?: string;
          venue_address?: string;
          entry_fee?: number;
          prize_pool?: number;
          first_prize?: number;
          second_prize?: number;
          third_prize?: number;
          prize_distribution?: Json;
          status?: string;
          management_status?: string;
          rules?: string | null;
          contact_info?: string | null;
          banner_image?: string | null;
          min_rank_requirement?: string | null;
          max_rank_requirement?: string | null;
          eligible_ranks?: Json;
          allow_all_ranks?: boolean;
          requires_approval?: boolean;
          is_public?: boolean;
          has_third_place_match?: boolean;
          created_by?: string;
          created_at?: string;
          updated_at?: string;
          venue_name?: string | null;
          start_date?: string | null;
          end_date?: string | null;
          registration_fee?: number;
          is_visible?: boolean;
          deleted_at?: string | null;
          tier?: string;
          elo_multiplier?: number;
          live_stream_url?: string | null;
          sponsor_info?: Json;
          spa_points_config?: Json;
          elo_points_config?: Json;
          comprehensive_rewards?: Json;
          special_rules?: Json;
          tournament_format_details?: Json;
          physical_prizes?: Json;
          winner_id?: string | null;
          parent_tournament_id?: string | null;
          tournament_format?: string | null;
          group_number?: string | null;
          group_assignment_method?: string | null;
        };
      };
      tournament_types: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          tournament_id: string;
          name: string;
        };
        Insert: {
          id?: string;
          created_at?: string | undefined;
          updated_at?: string | undefined;
          tournament_id?: string;
          name?: string | undefined;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          tournament_id?: string;
          name?: string;
        };
      };
      tournament_brackets: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          tournament_id: string;
          name: string;
        };
        Insert: {
          id?: string;
          created_at?: string | undefined;
          updated_at?: string | undefined;
          tournament_id?: string;
          name?: string | undefined;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          tournament_id?: string;
          name?: string;
        };
      };
      tournament_registrations: {
        Row: {
          id: string;
          tournament_id: string;
          user_id: string;
          registration_status: string;
          payment_status: string;
          registration_date: string;
          payment_date: string;
          notes: string;
          created_at: string;
          updated_at: string;
          player_id: string;
        };
        Insert: {
          id?: string;
          tournament_id?: string;
          user_id?: string | undefined;
          registration_status?: string | undefined;
          payment_status?: string | undefined;
          registration_date?: string | undefined;
          payment_date?: string | undefined;
          notes?: string | undefined;
          created_at?: string | undefined;
          updated_at?: string | undefined;
          player_id?: string;
        };
        Update: {
          id?: string;
          tournament_id?: string;
          user_id?: string;
          registration_status?: string;
          payment_status?: string;
          registration_date?: string;
          payment_date?: string;
          notes?: string;
          created_at?: string;
          updated_at?: string;
          player_id?: string;
        };
      };
      tournament_matches: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          tournament_id: string;
          name: string;
        };
        Insert: {
          id?: string;
          created_at?: string | undefined;
          updated_at?: string | undefined;
          tournament_id?: string;
          name?: string | undefined;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          tournament_id?: string;
          name?: string;
        };
      };
      tournament_rounds: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          tournament_id: string;
          name: string;
        };
        Insert: {
          id?: string;
          created_at?: string | undefined;
          updated_at?: string | undefined;
          tournament_id?: string;
          name?: string | undefined;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          tournament_id?: string;
          name?: string;
        };
      };
      tournament_settings: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          tournament_id: string;
          name: string;
        };
        Insert: {
          id?: string;
          created_at?: string | undefined;
          updated_at?: string | undefined;
          tournament_id?: string;
          name?: string | undefined;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          tournament_id?: string;
          name?: string;
        };
      };
      clubs: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          name: string;
          description: string | null;
          owner_id: string;
          is_public: boolean;
          member_count: number;
        };
        Insert: {
          id?: string;
          created_at?: string | undefined;
          updated_at?: string | undefined;
          name?: string | undefined;
          description?: string | null;
          owner_id?: string;
          is_public?: boolean | undefined;
          member_count?: number | undefined;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          name?: string;
          description?: string | null;
          owner_id?: string;
          is_public?: boolean;
          member_count?: number;
        };
      };
      club_members: {
        Row: {
          id: string;
          club_id: string;
          user_id: string;
          membership_type: string;
          membership_number: string;
          join_date: string;
          status: string;
          expiry_date: string | null;
          total_visits: number;
          last_visit: string | null;
          total_hours_played: number;
          preferred_table_types: string | null;
          preferred_time_slots: string | null;
          notification_preferences: Json;
          membership_fee: number;
          outstanding_balance: number;
          created_at: string;
          updated_at: string;
          role: string;
        };
        Insert: {
          id?: string;
          club_id?: string;
          user_id?: string | undefined;
          membership_type?: string | undefined;
          membership_number?: string | undefined;
          join_date?: string | undefined;
          status?: string | undefined;
          expiry_date?: string | null;
          total_visits?: number | undefined;
          last_visit?: string | null;
          total_hours_played?: number | undefined;
          preferred_table_types?: string | null;
          preferred_time_slots?: string | null;
          notification_preferences?: Json | undefined;
          membership_fee?: number | undefined;
          outstanding_balance?: number | undefined;
          created_at?: string | undefined;
          updated_at?: string | undefined;
          role?: string | undefined;
        };
        Update: {
          id?: string;
          club_id?: string;
          user_id?: string;
          membership_type?: string;
          membership_number?: string;
          join_date?: string;
          status?: string;
          expiry_date?: string | null;
          total_visits?: number;
          last_visit?: string | null;
          total_hours_played?: number;
          preferred_table_types?: string | null;
          preferred_time_slots?: string | null;
          notification_preferences?: Json;
          membership_fee?: number;
          outstanding_balance?: number;
          created_at?: string;
          updated_at?: string;
          role?: string;
        };
      };
      club_roles: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          club_id: string;
        };
        Insert: {
          id?: string;
          created_at?: string | undefined;
          updated_at?: string | undefined;
          club_id?: string;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          club_id?: string;
        };
      };
      club_settings: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          club_id: string;
        };
        Insert: {
          id?: string;
          created_at?: string | undefined;
          updated_at?: string | undefined;
          club_id?: string;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          club_id?: string;
        };
      };
      club_invitations: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          club_id: string;
        };
        Insert: {
          id?: string;
          created_at?: string | undefined;
          updated_at?: string | undefined;
          club_id?: string;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          club_id?: string;
        };
      };
      club_activities: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          club_id: string;
        };
        Insert: {
          id?: string;
          created_at?: string | undefined;
          updated_at?: string | undefined;
          club_id?: string;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          club_id?: string;
        };
      };
      wallets: {
        Row: {
          id: string;
          user_id: string;
          points_balance: number;
          total_earned: number;
          total_spent: number;
          created_at: string;
          updated_at: string;
          balance: number;
          status: string;
        };
        Insert: {
          id?: string;
          user_id?: string | undefined;
          points_balance?: number | undefined;
          total_earned?: number | undefined;
          total_spent?: number | undefined;
          created_at?: string | undefined;
          updated_at?: string | undefined;
          balance?: number | undefined;
          status?: string | undefined;
        };
        Update: {
          id?: string;
          user_id?: string;
          points_balance?: number;
          total_earned?: number;
          total_spent?: number;
          created_at?: string;
          updated_at?: string;
          balance?: number;
          status?: string;
        };
      };
      wallet_transactions: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          amount: number;
          currency: string;
        };
        Insert: {
          id?: string;
          created_at?: string | undefined;
          updated_at?: string | undefined;
          amount?: number | undefined;
          currency?: string | undefined;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          amount?: number;
          currency?: string;
        };
      };
      payment_transactions: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          amount: number;
          currency: string;
        };
        Insert: {
          id?: string;
          created_at?: string | undefined;
          updated_at?: string | undefined;
          amount?: number | undefined;
          currency?: string | undefined;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          amount?: number;
          currency?: string;
        };
      };
      payment_methods: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          amount: number;
          currency: string;
        };
        Insert: {
          id?: string;
          created_at?: string | undefined;
          updated_at?: string | undefined;
          amount?: number | undefined;
          currency?: string | undefined;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          amount?: number;
          currency?: string;
        };
      };
      billing_history: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          created_at?: string | undefined;
          updated_at?: string | undefined;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      invoices: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          created_at?: string | undefined;
          updated_at?: string | undefined;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      ranks: {
        Row: {
          id: string;
          code: string;
          rank_name: string;
          rank_order: number;
          elo_requirement: number;
          rank_color: string;
          description: string;
          created_at: string;
          updated_at: string;
          level: number;
        };
        Insert: {
          id?: string;
          code?: string | undefined;
          rank_name?: string | undefined;
          rank_order?: number | undefined;
          elo_requirement?: number | undefined;
          rank_color?: string | undefined;
          description?: string | undefined;
          created_at?: string | undefined;
          updated_at?: string | undefined;
          level?: number | undefined;
        };
        Update: {
          id?: string;
          code?: string;
          rank_name?: string;
          rank_order?: number;
          elo_requirement?: number;
          rank_color?: string;
          description?: string;
          created_at?: string;
          updated_at?: string;
          level?: number;
        };
      };
      rank_requirements: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          created_at?: string | undefined;
          updated_at?: string | undefined;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      ranking_history: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          created_at?: string | undefined;
          updated_at?: string | undefined;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      rank_calculations: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          created_at?: string | undefined;
          updated_at?: string | undefined;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      elo_history: {
        Row: {
          id: string;
          user_id: string;
          elo_change: number;
          new_elo: number;
          reason: string;
          match_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | undefined;
          elo_change?: number | undefined;
          new_elo?: number | undefined;
          reason?: string | undefined;
          match_id?: string | null;
          created_at?: string | undefined;
        };
        Update: {
          id?: string;
          user_id?: string;
          elo_change?: number;
          new_elo?: number;
          reason?: string;
          match_id?: string | null;
          created_at?: string;
        };
      };
      notifications: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          message: string;
          type: string;
          is_read: boolean;
          action_url: string;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
          auto_popup: boolean;
          priority: string;
          metadata: Json;
          club_id: string | null;
          category: string;
          challenge_id: string | null;
          tournament_id: string | null;
          match_id: string | null;
          icon: string;
          action_text: string | null;
          scheduled_for: string | null;
          expires_at: string | null;
          is_archived: boolean;
        };
        Insert: {
          id?: string;
          user_id?: string | undefined;
          title?: string | undefined;
          message?: string | undefined;
          type?: string | undefined;
          is_read?: boolean | undefined;
          action_url?: string | undefined;
          created_at?: string | undefined;
          updated_at?: string | undefined;
          deleted_at?: string | null;
          auto_popup?: boolean | undefined;
          priority?: string | undefined;
          metadata?: Json | undefined;
          club_id?: string | null;
          category?: string | undefined;
          challenge_id?: string | null;
          tournament_id?: string | null;
          match_id?: string | null;
          icon?: string | undefined;
          action_text?: string | null;
          scheduled_for?: string | null;
          expires_at?: string | null;
          is_archived?: boolean | undefined;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string;
          message?: string;
          type?: string;
          is_read?: boolean;
          action_url?: string;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          auto_popup?: boolean;
          priority?: string;
          metadata?: Json;
          club_id?: string | null;
          category?: string;
          challenge_id?: string | null;
          tournament_id?: string | null;
          match_id?: string | null;
          icon?: string;
          action_text?: string | null;
          scheduled_for?: string | null;
          expires_at?: string | null;
          is_archived?: boolean;
        };
      };
      notification_templates: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          user_id: string;
          title: string;
          message: string;
        };
        Insert: {
          id?: string;
          created_at?: string | undefined;
          updated_at?: string | undefined;
          user_id?: string | undefined;
          title?: string | undefined;
          message?: string | undefined;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          user_id?: string;
          title?: string;
          message?: string;
        };
      };
      notification_settings: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          user_id: string;
          title: string;
          message: string;
        };
        Insert: {
          id?: string;
          created_at?: string | undefined;
          updated_at?: string | undefined;
          user_id?: string | undefined;
          title?: string | undefined;
          message?: string | undefined;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          user_id?: string;
          title?: string;
          message?: string;
        };
      };
      messages: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          user_id: string;
          title: string;
          message: string;
        };
        Insert: {
          id?: string;
          created_at?: string | undefined;
          updated_at?: string | undefined;
          user_id?: string | undefined;
          title?: string | undefined;
          message?: string | undefined;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          user_id?: string;
          title?: string;
          message?: string;
        };
      };
      conversations: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          created_at?: string | undefined;
          updated_at?: string | undefined;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      communication_channels: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          created_at?: string | undefined;
          updated_at?: string | undefined;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      system_events: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          created_at?: string | undefined;
          updated_at?: string | undefined;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      analytics_events: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          created_at?: string | undefined;
          updated_at?: string | undefined;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      user_activities: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          id?: string;
          created_at?: string | undefined;
          updated_at?: string | undefined;
          user_id?: string | undefined;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          user_id?: string;
        };
      };
      performance_metrics: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          created_at?: string | undefined;
          updated_at?: string | undefined;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      usage_statistics: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          created_at?: string | undefined;
          updated_at?: string | undefined;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      achievements: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          created_at?: string | undefined;
          updated_at?: string | undefined;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      achievement_progress: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          created_at?: string | undefined;
          updated_at?: string | undefined;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      leaderboards: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          created_at?: string | undefined;
          updated_at?: string | undefined;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      rewards: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          created_at?: string | undefined;
          updated_at?: string | undefined;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      badges: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          created_at?: string | undefined;
          updated_at?: string | undefined;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      points_history: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          created_at?: string | undefined;
          updated_at?: string | undefined;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      settings: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          created_at?: string | undefined;
          updated_at?: string | undefined;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      system_config: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          created_at?: string | undefined;
          updated_at?: string | undefined;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      feature_flags: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          created_at?: string | undefined;
          updated_at?: string | undefined;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      maintenance_logs: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          created_at?: string | undefined;
          updated_at?: string | undefined;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      audit_logs: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          created_at?: string | undefined;
          updated_at?: string | undefined;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      news: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          created_at?: string | undefined;
          updated_at?: string | undefined;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      announcements: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          created_at?: string | undefined;
          updated_at?: string | undefined;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      tutorials: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          created_at?: string | undefined;
          updated_at?: string | undefined;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      media_files: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          created_at?: string | undefined;
          updated_at?: string | undefined;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      file_uploads: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          created_at?: string | undefined;
          updated_at?: string | undefined;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      venues: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          created_at?: string | undefined;
          updated_at?: string | undefined;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      tables: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          created_at?: string | undefined;
          updated_at?: string | undefined;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      table_bookings: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          created_at?: string | undefined;
          updated_at?: string | undefined;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      support_tickets: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          created_at?: string | undefined;
          updated_at?: string | undefined;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      faq: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          created_at?: string | undefined;
          updated_at?: string | undefined;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      help_articles: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          created_at?: string | undefined;
          updated_at?: string | undefined;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
  };
}


// Individual table interfaces
export interface Profiles {
  id: string;
  user_id: string;
  full_name: string | null;
  display_name: string | null;
  avatar_url: string | null;
  bio: string | null;
  verified_rank: string | null;
  elo: number;
  created_at: string;
  updated_at: string;
  is_admin: boolean;
  phone: string | null;
  skill_level: string;
  active_role: string;
  role: string;
  nickname: string | null;
  email: string | null;
  city: string | null;
  district: string | null;
  member_since: string;
  completion_percentage: number;
  is_demo_user: boolean;
  ban_status: string;
  ban_reason: string | null;
  banned_at: string | null;
  banned_by: string | null;
  cover_image_url: string | null;
  current_rank: string;
  spa_points: number;
  player_id: string;
  is_temp_player: boolean;
}

export interface Users {
  id: string;
  created_at: string;
  updated_at: string;
  email: string;
  phone: string | null;
  status: string;
}

export interface UserRoles {
  id: string;
  user_id: string;
  role: string;
  created_at: string;
  created_by: string | null;
}

export interface UserPreferences {
  id: string;
  created_at: string;
  updated_at: string;
  user_id: string;
}

export interface UserSessions {
  id: string;
  created_at: string;
  updated_at: string;
  user_id: string;
}

export interface AuthUsers {
  id: string;
  created_at: string;
  updated_at: string;
  user_id: string;
}

export interface AuthSessions {
  id: string;
  created_at: string;
  updated_at: string;
}

export interface AuthRefreshTokens {
  id: string;
  created_at: string;
  updated_at: string;
}

export interface Challenges {
  id: string;
  challenger_id: string;
  opponent_id: string | null;
  status: string;
  challenge_message: string | null;
  response_message: string | null;
  created_at: string;
  responded_at: string | null;
  completed_at: string | null;
  is_open_challenge: boolean;
  bet_points: number;
  race_to: number;
  handicap_1_rank: string;
  handicap_05_rank: string;
  message: string;
  expires_at: string;
  challenge_type: string;
  handicap_data: Json;
  club_id: string;
  scheduled_time: string | null;
  challenger_score: number;
  opponent_score: number;
  winner_id: string | null;
  started_at: string | null;
  updated_at: string;
  challenger_name: string;
  location: string;
  required_rank: string;
  is_sabo: boolean;
  club_confirmed: boolean;
  club_confirmed_at: string | null;
  club_confirmed_by: string | null;
  club_note: string | null;
  challenger_player_id: string;
  opponent_player_id: string | null;
  bet_amount: number;
}

export interface ChallengeParticipants {
  id: string;
  created_at: string;
  updated_at: string;
}

export interface ChallengeTypes {
  id: string;
  created_at: string;
  updated_at: string;
}

export interface GameSessions {
  id: string;
  created_at: string;
  updated_at: string;
}

export interface GameResults {
  id: string;
  created_at: string;
  updated_at: string;
}

export interface Shots {
  id: string;
  created_at: string;
  updated_at: string;
}

export interface ShotAnalysis {
  id: string;
  created_at: string;
  updated_at: string;
}

export interface GameMechanics {
  id: string;
  created_at: string;
  updated_at: string;
}

export interface GameSettings {
  id: string;
  created_at: string;
  updated_at: string;
}

export interface Tournaments {
  id: string;
  name: string;
  description: string;
  tournament_type: string;
  game_format: string;
  tier_level: number;
  max_participants: number;
  current_participants: number;
  tournament_start: string;
  tournament_end: string;
  registration_start: string;
  registration_end: string;
  club_id: string;
  venue_address: string;
  entry_fee: number;
  prize_pool: number;
  first_prize: number;
  second_prize: number;
  third_prize: number;
  prize_distribution: Json;
  status: string;
  management_status: string;
  rules: string | null;
  contact_info: string | null;
  banner_image: string | null;
  min_rank_requirement: string | null;
  max_rank_requirement: string | null;
  eligible_ranks: Json;
  allow_all_ranks: boolean;
  requires_approval: boolean;
  is_public: boolean;
  has_third_place_match: boolean;
  created_by: string;
  created_at: string;
  updated_at: string;
  venue_name: string | null;
  start_date: string | null;
  end_date: string | null;
  registration_fee: number;
  is_visible: boolean;
  deleted_at: string | null;
  tier: string;
  elo_multiplier: number;
  live_stream_url: string | null;
  sponsor_info: Json;
  spa_points_config: Json;
  elo_points_config: Json;
  comprehensive_rewards: Json;
  special_rules: Json;
  tournament_format_details: Json;
  physical_prizes: Json;
  winner_id: string | null;
  parent_tournament_id: string | null;
  tournament_format: string | null;
  group_number: string | null;
  group_assignment_method: string | null;
}

export interface TournamentTypes {
  id: string;
  created_at: string;
  updated_at: string;
  tournament_id: string;
  name: string;
}

export interface TournamentBrackets {
  id: string;
  created_at: string;
  updated_at: string;
  tournament_id: string;
  name: string;
}

export interface TournamentRegistrations {
  id: string;
  tournament_id: string;
  user_id: string;
  registration_status: string;
  payment_status: string;
  registration_date: string;
  payment_date: string;
  notes: string;
  created_at: string;
  updated_at: string;
  player_id: string;
}

export interface TournamentMatches {
  id: string;
  created_at: string;
  updated_at: string;
  tournament_id: string;
  name: string;
}

export interface TournamentRounds {
  id: string;
  created_at: string;
  updated_at: string;
  tournament_id: string;
  name: string;
}

export interface TournamentSettings {
  id: string;
  created_at: string;
  updated_at: string;
  tournament_id: string;
  name: string;
}

export interface Clubs {
  id: string;
  created_at: string;
  updated_at: string;
  name: string;
  description: string | null;
  owner_id: string;
  is_public: boolean;
  member_count: number;
}

export interface ClubMembers {
  id: string;
  club_id: string;
  user_id: string;
  membership_type: string;
  membership_number: string;
  join_date: string;
  status: string;
  expiry_date: string | null;
  total_visits: number;
  last_visit: string | null;
  total_hours_played: number;
  preferred_table_types: string | null;
  preferred_time_slots: string | null;
  notification_preferences: Json;
  membership_fee: number;
  outstanding_balance: number;
  created_at: string;
  updated_at: string;
  role: string;
}

export interface ClubRoles {
  id: string;
  created_at: string;
  updated_at: string;
  club_id: string;
}

export interface ClubSettings {
  id: string;
  created_at: string;
  updated_at: string;
  club_id: string;
}

export interface ClubInvitations {
  id: string;
  created_at: string;
  updated_at: string;
  club_id: string;
}

export interface ClubActivities {
  id: string;
  created_at: string;
  updated_at: string;
  club_id: string;
}

export interface Wallets {
  id: string;
  user_id: string;
  points_balance: number;
  total_earned: number;
  total_spent: number;
  created_at: string;
  updated_at: string;
  balance: number;
  status: string;
}

export interface WalletTransactions {
  id: string;
  created_at: string;
  updated_at: string;
  amount: number;
  currency: string;
}

export interface PaymentTransactions {
  id: string;
  created_at: string;
  updated_at: string;
  amount: number;
  currency: string;
}

export interface PaymentMethods {
  id: string;
  created_at: string;
  updated_at: string;
  amount: number;
  currency: string;
}

export interface BillingHistory {
  id: string;
  created_at: string;
  updated_at: string;
}

export interface Invoices {
  id: string;
  created_at: string;
  updated_at: string;
}

export interface Ranks {
  id: string;
  code: string;
  rank_name: string;
  rank_order: number;
  elo_requirement: number;
  rank_color: string;
  description: string;
  created_at: string;
  updated_at: string;
  level: number;
}

export interface RankRequirements {
  id: string;
  created_at: string;
  updated_at: string;
}

export interface RankingHistory {
  id: string;
  created_at: string;
  updated_at: string;
}

export interface RankCalculations {
  id: string;
  created_at: string;
  updated_at: string;
}

export interface EloHistory {
  id: string;
  user_id: string;
  elo_change: number;
  new_elo: number;
  reason: string;
  match_id: string | null;
  created_at: string;
}

export interface Notifications {
  id: string;
  user_id: string;
  title: string;
  message: string;
  type: string;
  is_read: boolean;
  action_url: string;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
  auto_popup: boolean;
  priority: string;
  metadata: Json;
  club_id: string | null;
  category: string;
  challenge_id: string | null;
  tournament_id: string | null;
  match_id: string | null;
  icon: string;
  action_text: string | null;
  scheduled_for: string | null;
  expires_at: string | null;
  is_archived: boolean;
}

export interface NotificationTemplates {
  id: string;
  created_at: string;
  updated_at: string;
  user_id: string;
  title: string;
  message: string;
}

export interface NotificationSettings {
  id: string;
  created_at: string;
  updated_at: string;
  user_id: string;
  title: string;
  message: string;
}

export interface Messages {
  id: string;
  created_at: string;
  updated_at: string;
  user_id: string;
  title: string;
  message: string;
}

export interface Conversations {
  id: string;
  created_at: string;
  updated_at: string;
}

export interface CommunicationChannels {
  id: string;
  created_at: string;
  updated_at: string;
}

export interface SystemEvents {
  id: string;
  created_at: string;
  updated_at: string;
}

export interface AnalyticsEvents {
  id: string;
  created_at: string;
  updated_at: string;
}

export interface UserActivities {
  id: string;
  created_at: string;
  updated_at: string;
  user_id: string;
}

export interface PerformanceMetrics {
  id: string;
  created_at: string;
  updated_at: string;
}

export interface UsageStatistics {
  id: string;
  created_at: string;
  updated_at: string;
}

export interface Achievements {
  id: string;
  created_at: string;
  updated_at: string;
}

export interface AchievementProgress {
  id: string;
  created_at: string;
  updated_at: string;
}

export interface Leaderboards {
  id: string;
  created_at: string;
  updated_at: string;
}

export interface Rewards {
  id: string;
  created_at: string;
  updated_at: string;
}

export interface Badges {
  id: string;
  created_at: string;
  updated_at: string;
}

export interface PointsHistory {
  id: string;
  created_at: string;
  updated_at: string;
}

export interface Settings {
  id: string;
  created_at: string;
  updated_at: string;
}

export interface SystemConfig {
  id: string;
  created_at: string;
  updated_at: string;
}

export interface FeatureFlags {
  id: string;
  created_at: string;
  updated_at: string;
}

export interface MaintenanceLogs {
  id: string;
  created_at: string;
  updated_at: string;
}

export interface AuditLogs {
  id: string;
  created_at: string;
  updated_at: string;
}

export interface News {
  id: string;
  created_at: string;
  updated_at: string;
}

export interface Announcements {
  id: string;
  created_at: string;
  updated_at: string;
}

export interface Tutorials {
  id: string;
  created_at: string;
  updated_at: string;
}

export interface MediaFiles {
  id: string;
  created_at: string;
  updated_at: string;
}

export interface FileUploads {
  id: string;
  created_at: string;
  updated_at: string;
}

export interface Venues {
  id: string;
  created_at: string;
  updated_at: string;
}

export interface Tables {
  id: string;
  created_at: string;
  updated_at: string;
}

export interface TableBookings {
  id: string;
  created_at: string;
  updated_at: string;
}

export interface SupportTickets {
  id: string;
  created_at: string;
  updated_at: string;
}

export interface Faq {
  id: string;
  created_at: string;
  updated_at: string;
}

export interface HelpArticles {
  id: string;
  created_at: string;
  updated_at: string;
}



// Export type aliases for convenience
export type ProfilesRow = Database['public']['Tables']['profiles']['Row'];
export type UsersRow = Database['public']['Tables']['users']['Row'];
export type UserRolesRow = Database['public']['Tables']['user_roles']['Row'];
export type UserPreferencesRow = Database['public']['Tables']['user_preferences']['Row'];
export type UserSessionsRow = Database['public']['Tables']['user_sessions']['Row'];
export type AuthUsersRow = Database['public']['Tables']['auth_users']['Row'];
export type AuthSessionsRow = Database['public']['Tables']['auth_sessions']['Row'];
export type AuthRefreshTokensRow = Database['public']['Tables']['auth_refresh_tokens']['Row'];
export type ChallengesRow = Database['public']['Tables']['challenges']['Row'];
export type ChallengeParticipantsRow = Database['public']['Tables']['challenge_participants']['Row'];
export type ChallengeTypesRow = Database['public']['Tables']['challenge_types']['Row'];
export type GameSessionsRow = Database['public']['Tables']['game_sessions']['Row'];
export type GameResultsRow = Database['public']['Tables']['game_results']['Row'];
export type ShotsRow = Database['public']['Tables']['shots']['Row'];
export type ShotAnalysisRow = Database['public']['Tables']['shot_analysis']['Row'];
export type GameMechanicsRow = Database['public']['Tables']['game_mechanics']['Row'];
export type GameSettingsRow = Database['public']['Tables']['game_settings']['Row'];
export type TournamentsRow = Database['public']['Tables']['tournaments']['Row'];
export type TournamentTypesRow = Database['public']['Tables']['tournament_types']['Row'];
export type TournamentBracketsRow = Database['public']['Tables']['tournament_brackets']['Row'];
export type TournamentRegistrationsRow = Database['public']['Tables']['tournament_registrations']['Row'];
export type TournamentMatchesRow = Database['public']['Tables']['tournament_matches']['Row'];
export type TournamentRoundsRow = Database['public']['Tables']['tournament_rounds']['Row'];
export type TournamentSettingsRow = Database['public']['Tables']['tournament_settings']['Row'];
export type ClubsRow = Database['public']['Tables']['clubs']['Row'];
export type ClubMembersRow = Database['public']['Tables']['club_members']['Row'];
export type ClubRolesRow = Database['public']['Tables']['club_roles']['Row'];
export type ClubSettingsRow = Database['public']['Tables']['club_settings']['Row'];
export type ClubInvitationsRow = Database['public']['Tables']['club_invitations']['Row'];
export type ClubActivitiesRow = Database['public']['Tables']['club_activities']['Row'];
export type WalletsRow = Database['public']['Tables']['wallets']['Row'];
export type WalletTransactionsRow = Database['public']['Tables']['wallet_transactions']['Row'];
export type PaymentTransactionsRow = Database['public']['Tables']['payment_transactions']['Row'];
export type PaymentMethodsRow = Database['public']['Tables']['payment_methods']['Row'];
export type BillingHistoryRow = Database['public']['Tables']['billing_history']['Row'];
export type InvoicesRow = Database['public']['Tables']['invoices']['Row'];
export type RanksRow = Database['public']['Tables']['ranks']['Row'];
export type RankRequirementsRow = Database['public']['Tables']['rank_requirements']['Row'];
export type RankingHistoryRow = Database['public']['Tables']['ranking_history']['Row'];
export type RankCalculationsRow = Database['public']['Tables']['rank_calculations']['Row'];
export type EloHistoryRow = Database['public']['Tables']['elo_history']['Row'];
export type NotificationsRow = Database['public']['Tables']['notifications']['Row'];
export type NotificationTemplatesRow = Database['public']['Tables']['notification_templates']['Row'];
export type NotificationSettingsRow = Database['public']['Tables']['notification_settings']['Row'];
export type MessagesRow = Database['public']['Tables']['messages']['Row'];
export type ConversationsRow = Database['public']['Tables']['conversations']['Row'];
export type CommunicationChannelsRow = Database['public']['Tables']['communication_channels']['Row'];
export type SystemEventsRow = Database['public']['Tables']['system_events']['Row'];
export type AnalyticsEventsRow = Database['public']['Tables']['analytics_events']['Row'];
export type UserActivitiesRow = Database['public']['Tables']['user_activities']['Row'];
export type PerformanceMetricsRow = Database['public']['Tables']['performance_metrics']['Row'];
export type UsageStatisticsRow = Database['public']['Tables']['usage_statistics']['Row'];
export type AchievementsRow = Database['public']['Tables']['achievements']['Row'];
export type AchievementProgressRow = Database['public']['Tables']['achievement_progress']['Row'];
export type LeaderboardsRow = Database['public']['Tables']['leaderboards']['Row'];
export type RewardsRow = Database['public']['Tables']['rewards']['Row'];
export type BadgesRow = Database['public']['Tables']['badges']['Row'];
export type PointsHistoryRow = Database['public']['Tables']['points_history']['Row'];
export type SettingsRow = Database['public']['Tables']['settings']['Row'];
export type SystemConfigRow = Database['public']['Tables']['system_config']['Row'];
export type FeatureFlagsRow = Database['public']['Tables']['feature_flags']['Row'];
export type MaintenanceLogsRow = Database['public']['Tables']['maintenance_logs']['Row'];
export type AuditLogsRow = Database['public']['Tables']['audit_logs']['Row'];
export type NewsRow = Database['public']['Tables']['news']['Row'];
export type AnnouncementsRow = Database['public']['Tables']['announcements']['Row'];
export type TutorialsRow = Database['public']['Tables']['tutorials']['Row'];
export type MediaFilesRow = Database['public']['Tables']['media_files']['Row'];
export type FileUploadsRow = Database['public']['Tables']['file_uploads']['Row'];
export type VenuesRow = Database['public']['Tables']['venues']['Row'];
export type TablesRow = Database['public']['Tables']['tables']['Row'];
export type TableBookingsRow = Database['public']['Tables']['table_bookings']['Row'];
export type SupportTicketsRow = Database['public']['Tables']['support_tickets']['Row'];
export type FaqRow = Database['public']['Tables']['faq']['Row'];
export type HelpArticlesRow = Database['public']['Tables']['help_articles']['Row'];

export type ProfilesInsert = Database['public']['Tables']['profiles']['Insert'];
export type UsersInsert = Database['public']['Tables']['users']['Insert'];
export type UserRolesInsert = Database['public']['Tables']['user_roles']['Insert'];
export type UserPreferencesInsert = Database['public']['Tables']['user_preferences']['Insert'];
export type UserSessionsInsert = Database['public']['Tables']['user_sessions']['Insert'];
export type AuthUsersInsert = Database['public']['Tables']['auth_users']['Insert'];
export type AuthSessionsInsert = Database['public']['Tables']['auth_sessions']['Insert'];
export type AuthRefreshTokensInsert = Database['public']['Tables']['auth_refresh_tokens']['Insert'];
export type ChallengesInsert = Database['public']['Tables']['challenges']['Insert'];
export type ChallengeParticipantsInsert = Database['public']['Tables']['challenge_participants']['Insert'];
export type ChallengeTypesInsert = Database['public']['Tables']['challenge_types']['Insert'];
export type GameSessionsInsert = Database['public']['Tables']['game_sessions']['Insert'];
export type GameResultsInsert = Database['public']['Tables']['game_results']['Insert'];
export type ShotsInsert = Database['public']['Tables']['shots']['Insert'];
export type ShotAnalysisInsert = Database['public']['Tables']['shot_analysis']['Insert'];
export type GameMechanicsInsert = Database['public']['Tables']['game_mechanics']['Insert'];
export type GameSettingsInsert = Database['public']['Tables']['game_settings']['Insert'];
export type TournamentsInsert = Database['public']['Tables']['tournaments']['Insert'];
export type TournamentTypesInsert = Database['public']['Tables']['tournament_types']['Insert'];
export type TournamentBracketsInsert = Database['public']['Tables']['tournament_brackets']['Insert'];
export type TournamentRegistrationsInsert = Database['public']['Tables']['tournament_registrations']['Insert'];
export type TournamentMatchesInsert = Database['public']['Tables']['tournament_matches']['Insert'];
export type TournamentRoundsInsert = Database['public']['Tables']['tournament_rounds']['Insert'];
export type TournamentSettingsInsert = Database['public']['Tables']['tournament_settings']['Insert'];
export type ClubsInsert = Database['public']['Tables']['clubs']['Insert'];
export type ClubMembersInsert = Database['public']['Tables']['club_members']['Insert'];
export type ClubRolesInsert = Database['public']['Tables']['club_roles']['Insert'];
export type ClubSettingsInsert = Database['public']['Tables']['club_settings']['Insert'];
export type ClubInvitationsInsert = Database['public']['Tables']['club_invitations']['Insert'];
export type ClubActivitiesInsert = Database['public']['Tables']['club_activities']['Insert'];
export type WalletsInsert = Database['public']['Tables']['wallets']['Insert'];
export type WalletTransactionsInsert = Database['public']['Tables']['wallet_transactions']['Insert'];
export type PaymentTransactionsInsert = Database['public']['Tables']['payment_transactions']['Insert'];
export type PaymentMethodsInsert = Database['public']['Tables']['payment_methods']['Insert'];
export type BillingHistoryInsert = Database['public']['Tables']['billing_history']['Insert'];
export type InvoicesInsert = Database['public']['Tables']['invoices']['Insert'];
export type RanksInsert = Database['public']['Tables']['ranks']['Insert'];
export type RankRequirementsInsert = Database['public']['Tables']['rank_requirements']['Insert'];
export type RankingHistoryInsert = Database['public']['Tables']['ranking_history']['Insert'];
export type RankCalculationsInsert = Database['public']['Tables']['rank_calculations']['Insert'];
export type EloHistoryInsert = Database['public']['Tables']['elo_history']['Insert'];
export type NotificationsInsert = Database['public']['Tables']['notifications']['Insert'];
export type NotificationTemplatesInsert = Database['public']['Tables']['notification_templates']['Insert'];
export type NotificationSettingsInsert = Database['public']['Tables']['notification_settings']['Insert'];
export type MessagesInsert = Database['public']['Tables']['messages']['Insert'];
export type ConversationsInsert = Database['public']['Tables']['conversations']['Insert'];
export type CommunicationChannelsInsert = Database['public']['Tables']['communication_channels']['Insert'];
export type SystemEventsInsert = Database['public']['Tables']['system_events']['Insert'];
export type AnalyticsEventsInsert = Database['public']['Tables']['analytics_events']['Insert'];
export type UserActivitiesInsert = Database['public']['Tables']['user_activities']['Insert'];
export type PerformanceMetricsInsert = Database['public']['Tables']['performance_metrics']['Insert'];
export type UsageStatisticsInsert = Database['public']['Tables']['usage_statistics']['Insert'];
export type AchievementsInsert = Database['public']['Tables']['achievements']['Insert'];
export type AchievementProgressInsert = Database['public']['Tables']['achievement_progress']['Insert'];
export type LeaderboardsInsert = Database['public']['Tables']['leaderboards']['Insert'];
export type RewardsInsert = Database['public']['Tables']['rewards']['Insert'];
export type BadgesInsert = Database['public']['Tables']['badges']['Insert'];
export type PointsHistoryInsert = Database['public']['Tables']['points_history']['Insert'];
export type SettingsInsert = Database['public']['Tables']['settings']['Insert'];
export type SystemConfigInsert = Database['public']['Tables']['system_config']['Insert'];
export type FeatureFlagsInsert = Database['public']['Tables']['feature_flags']['Insert'];
export type MaintenanceLogsInsert = Database['public']['Tables']['maintenance_logs']['Insert'];
export type AuditLogsInsert = Database['public']['Tables']['audit_logs']['Insert'];
export type NewsInsert = Database['public']['Tables']['news']['Insert'];
export type AnnouncementsInsert = Database['public']['Tables']['announcements']['Insert'];
export type TutorialsInsert = Database['public']['Tables']['tutorials']['Insert'];
export type MediaFilesInsert = Database['public']['Tables']['media_files']['Insert'];
export type FileUploadsInsert = Database['public']['Tables']['file_uploads']['Insert'];
export type VenuesInsert = Database['public']['Tables']['venues']['Insert'];
export type TablesInsert = Database['public']['Tables']['tables']['Insert'];
export type TableBookingsInsert = Database['public']['Tables']['table_bookings']['Insert'];
export type SupportTicketsInsert = Database['public']['Tables']['support_tickets']['Insert'];
export type FaqInsert = Database['public']['Tables']['faq']['Insert'];
export type HelpArticlesInsert = Database['public']['Tables']['help_articles']['Insert'];

export type ProfilesUpdate = Database['public']['Tables']['profiles']['Update'];
export type UsersUpdate = Database['public']['Tables']['users']['Update'];
export type UserRolesUpdate = Database['public']['Tables']['user_roles']['Update'];
export type UserPreferencesUpdate = Database['public']['Tables']['user_preferences']['Update'];
export type UserSessionsUpdate = Database['public']['Tables']['user_sessions']['Update'];
export type AuthUsersUpdate = Database['public']['Tables']['auth_users']['Update'];
export type AuthSessionsUpdate = Database['public']['Tables']['auth_sessions']['Update'];
export type AuthRefreshTokensUpdate = Database['public']['Tables']['auth_refresh_tokens']['Update'];
export type ChallengesUpdate = Database['public']['Tables']['challenges']['Update'];
export type ChallengeParticipantsUpdate = Database['public']['Tables']['challenge_participants']['Update'];
export type ChallengeTypesUpdate = Database['public']['Tables']['challenge_types']['Update'];
export type GameSessionsUpdate = Database['public']['Tables']['game_sessions']['Update'];
export type GameResultsUpdate = Database['public']['Tables']['game_results']['Update'];
export type ShotsUpdate = Database['public']['Tables']['shots']['Update'];
export type ShotAnalysisUpdate = Database['public']['Tables']['shot_analysis']['Update'];
export type GameMechanicsUpdate = Database['public']['Tables']['game_mechanics']['Update'];
export type GameSettingsUpdate = Database['public']['Tables']['game_settings']['Update'];
export type TournamentsUpdate = Database['public']['Tables']['tournaments']['Update'];
export type TournamentTypesUpdate = Database['public']['Tables']['tournament_types']['Update'];
export type TournamentBracketsUpdate = Database['public']['Tables']['tournament_brackets']['Update'];
export type TournamentRegistrationsUpdate = Database['public']['Tables']['tournament_registrations']['Update'];
export type TournamentMatchesUpdate = Database['public']['Tables']['tournament_matches']['Update'];
export type TournamentRoundsUpdate = Database['public']['Tables']['tournament_rounds']['Update'];
export type TournamentSettingsUpdate = Database['public']['Tables']['tournament_settings']['Update'];
export type ClubsUpdate = Database['public']['Tables']['clubs']['Update'];
export type ClubMembersUpdate = Database['public']['Tables']['club_members']['Update'];
export type ClubRolesUpdate = Database['public']['Tables']['club_roles']['Update'];
export type ClubSettingsUpdate = Database['public']['Tables']['club_settings']['Update'];
export type ClubInvitationsUpdate = Database['public']['Tables']['club_invitations']['Update'];
export type ClubActivitiesUpdate = Database['public']['Tables']['club_activities']['Update'];
export type WalletsUpdate = Database['public']['Tables']['wallets']['Update'];
export type WalletTransactionsUpdate = Database['public']['Tables']['wallet_transactions']['Update'];
export type PaymentTransactionsUpdate = Database['public']['Tables']['payment_transactions']['Update'];
export type PaymentMethodsUpdate = Database['public']['Tables']['payment_methods']['Update'];
export type BillingHistoryUpdate = Database['public']['Tables']['billing_history']['Update'];
export type InvoicesUpdate = Database['public']['Tables']['invoices']['Update'];
export type RanksUpdate = Database['public']['Tables']['ranks']['Update'];
export type RankRequirementsUpdate = Database['public']['Tables']['rank_requirements']['Update'];
export type RankingHistoryUpdate = Database['public']['Tables']['ranking_history']['Update'];
export type RankCalculationsUpdate = Database['public']['Tables']['rank_calculations']['Update'];
export type EloHistoryUpdate = Database['public']['Tables']['elo_history']['Update'];
export type NotificationsUpdate = Database['public']['Tables']['notifications']['Update'];
export type NotificationTemplatesUpdate = Database['public']['Tables']['notification_templates']['Update'];
export type NotificationSettingsUpdate = Database['public']['Tables']['notification_settings']['Update'];
export type MessagesUpdate = Database['public']['Tables']['messages']['Update'];
export type ConversationsUpdate = Database['public']['Tables']['conversations']['Update'];
export type CommunicationChannelsUpdate = Database['public']['Tables']['communication_channels']['Update'];
export type SystemEventsUpdate = Database['public']['Tables']['system_events']['Update'];
export type AnalyticsEventsUpdate = Database['public']['Tables']['analytics_events']['Update'];
export type UserActivitiesUpdate = Database['public']['Tables']['user_activities']['Update'];
export type PerformanceMetricsUpdate = Database['public']['Tables']['performance_metrics']['Update'];
export type UsageStatisticsUpdate = Database['public']['Tables']['usage_statistics']['Update'];
export type AchievementsUpdate = Database['public']['Tables']['achievements']['Update'];
export type AchievementProgressUpdate = Database['public']['Tables']['achievement_progress']['Update'];
export type LeaderboardsUpdate = Database['public']['Tables']['leaderboards']['Update'];
export type RewardsUpdate = Database['public']['Tables']['rewards']['Update'];
export type BadgesUpdate = Database['public']['Tables']['badges']['Update'];
export type PointsHistoryUpdate = Database['public']['Tables']['points_history']['Update'];
export type SettingsUpdate = Database['public']['Tables']['settings']['Update'];
export type SystemConfigUpdate = Database['public']['Tables']['system_config']['Update'];
export type FeatureFlagsUpdate = Database['public']['Tables']['feature_flags']['Update'];
export type MaintenanceLogsUpdate = Database['public']['Tables']['maintenance_logs']['Update'];
export type AuditLogsUpdate = Database['public']['Tables']['audit_logs']['Update'];
export type NewsUpdate = Database['public']['Tables']['news']['Update'];
export type AnnouncementsUpdate = Database['public']['Tables']['announcements']['Update'];
export type TutorialsUpdate = Database['public']['Tables']['tutorials']['Update'];
export type MediaFilesUpdate = Database['public']['Tables']['media_files']['Update'];
export type FileUploadsUpdate = Database['public']['Tables']['file_uploads']['Update'];
export type VenuesUpdate = Database['public']['Tables']['venues']['Update'];
export type TablesUpdate = Database['public']['Tables']['tables']['Update'];
export type TableBookingsUpdate = Database['public']['Tables']['table_bookings']['Update'];
export type SupportTicketsUpdate = Database['public']['Tables']['support_tickets']['Update'];
export type FaqUpdate = Database['public']['Tables']['faq']['Update'];
export type HelpArticlesUpdate = Database['public']['Tables']['help_articles']['Update'];
