name: sabo_flutter
description: SABO Pool Arena Mobile App - Flutter Version
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # State Management - Modern Riverpod
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # Navigation - Type-safe GoRouter
  go_router: ^12.1.3
  
  # HTTP & API
  dio: ^5.4.0
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  http: ^1.1.0
  
  # Database
  supabase_flutter: ^2.3.4
  
  # UI & Design
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  flutter_hooks: ^0.20.3
  hooks_riverpod: ^2.4.9
  
  # Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  
  # Payment & WebView
  webview_flutter: ^4.4.2
  url_launcher: ^6.2.2
  
  # Native Device Features
  image_picker: ^1.0.4
  permission_handler: ^11.0.1
  local_auth: ^2.1.6
  local_auth_android: ^1.0.34
  local_auth_ios: ^1.0.15
  connectivity_plus: ^5.0.1
  device_info_plus: ^9.1.0
  
  # Push Notifications (Future)
  # firebase_messaging: ^14.7.0
  # firebase_core: ^2.15.1
  
  # Utils
  freezed_annotation: ^2.4.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  
  # Code Generation
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  custom_lint: ^0.5.7
  riverpod_lint: ^2.3.7
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.6
  freezed: ^2.4.6
  go_router_builder: ^2.4.1

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
